### ISSUE TITLE
关于多线程扫描与license

### ISSUE THREAD

**Issue by FunnyWolf** [Adminisme/ServerScan#1]
你好,portscan.go中端口扫描是使用多线程的方式,扫描一个ip的全端口(1-65535)需要7分钟,使用协成方式是否会提升扫描效率.
另外项目中未看到license文件,请问项目是要使用什么开源协议?

**Comment by Adminisme** [comment]
您好，多谢师傅的提议。

portscan.go中使用的端口扫描是使用的是协程并发嵌套，扫描时间较长的原因：
1、因为为了保障低权限用户的可用性，采用了tcp的超时机制来实现了检测端口存活，其次就是每个端口设置了较长的超时时长。
2、协程并发数量和操作系统有关，扫描一个IP的全端口(1-65535)，在Win需要7分钟，但是在Linux可能却只需要2-3分钟。后期会增加操作系统的判断而选择相应的协程并发数。

感谢师傅提到关于项目中未看到license文件的问题，该项目开源协议主要目前使用：GNU General Public Licence (GPL)协议。
但也需要遵守项目中的其他补充条款，如：禁止商业使用，不得将其用于非法用途及盈利等目的。

感谢师傅支持ServerScan，非常欢迎您一起改进ServerScan。
祝好！
