### ISSUE TITLE
Releases中的mac版运行失败

### ISSUE THREAD

**Issue by SewellDinG** [Adminisme/ServerScan#2]
师傅你好，当前Releases中的mac版运行失败，ServerScan_Air_v1.0.2_darwin_amd64和ServerScan_Pro_v1.0.2_darwin_amd64，环境macOS Catalina 10.15.2。
```
[Sewell]: ~/Downloads
➜  ./ServerScan_Air_v1.0.2_darwin_amd64
[1]    1817 killed     ./ServerScan_Air_v1.0.2_darwin_amd64
[Sewell]: ~/Downloads
➜  ./ServerScan_Pro_v1.0.2_darwin_amd64
[1]    2362 killed     ./ServerScan_Pro_v1.0.2_darwin_amd64
```
本地编译是可以运行的，可能是师傅你在win上编译的mac版导致的。

**Comment by Adminisme** [comment]
感谢师傅发现此问题。
在win上编译的mac版是没有问题的，主要原因是为了减少体积，Releases中的文件使用了”upx -9“ 压缩了文件，导致破坏了文件结构。如果要运行当前版本，可以使用“upx -d”还原文件结构。
