### ISSUE TITLE
可以支持socks代理扫描吗

### ISSUE THREAD

**Issue by Feidao-fei** [Adminisme/ServerScan#4]
尝试用socks5代理扫描的时候，proxychains ./ServerScan_Pro_v1.0.2_linux_adm64 -h ip -m tcp不行
没有任何结果

**Comment by Adminisme** [comment]
ServerScan设计的初衷是将其放置于内网服务器进行扫描的，同时不建议配合代理使用。
由于程序本身扫描时发包的频率过高，在扫描期间会导致代理不可用。

**Comment by Adminisme** [comment]
过段时间将会再次更新ServerScan，新增扫描线程参数，可以利用低线程扫描配合代理扫描内网。
